[toolchain]
anchor_version = "0.29.0"
solana_version = "1.17.22"

[features]
seeds = false
skip-lint = false

[programs.localnet]
ntt_relayer = "9jFBLvMZZERVmeY4tbq5MejbXRE18paGEuoB6xVJZgGe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/brain/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
